# Generated by Django 5.0.6 on 2024-05-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_year", models.IntegerField(blank=True, null=True)),
                ("intensity", models.IntegerField(blank=True, null=True)),
                ("sector", models.CharField(blank=True, max_length=225, null=True)),
                ("topic", models.CharField(blank=True, max_length=225, null=True)),
                ("insight", models.CharField(blank=True, max_length=1000, null=True)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("region", models.CharField(blank=True, max_length=225, null=True)),
                ("start_year", models.IntegerField(blank=True, null=True)),
                ("impact", models.CharField(blank=True, max_length=225, null=True)),
                ("added", models.DateTimeField(blank=True, null=True)),
                ("published", models.DateTimeField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=225, null=True)),
                ("relevance", models.IntegerField(blank=True, null=True)),
                ("pestle", models.CharField(blank=True, max_length=225, null=True)),
                ("source", models.CharField(blank=True, max_length=225, null=True)),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("likelihood", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
